---
- name: Perform vMotion of VM to {{dest_ESXi}}
  local_action:
    module: vmware_vmotion
    hostname: "{{vsphere_vcenter}}"
    username: "{{vsphere_vcusername}}"
    password: "{{vsphere_vcpassword}}"
    validate_certs: False
    vm_name: "{{item}}"
    destination_host: "{{dest_ESXi}}" 
  with_items: "{{vm_names}}"  