---
- name: check afg oid {{ip_oam}}
  shell: >
    snmpwalk
    -v 2c
    -c publicMiep
    "{{ip_oam}}:161"
    "{{item}}"
  with_items: "{{OIDs}}"
  register: rst

- name: result list
  set_fact:
    oid_rst: "{{oid_rst | default([]) + item.stdout_lines}}"
  with_items:
    - "{{rst.results}}"   

- debug: msg="{{oid_rst}}"

- set_fact: 
    oid_rst: []

