---
- debug: msg="this is vsphere test for {{ vsphere_vcenter }}"

- name: "Get esxi hosts and resource pools from connected vSphere" 
  action:  
    module: vsphere_list_hosts
    vcenter: "{{ vsphere_vcenter }}"
    vcusername: "{{ vsphere_vcusername }}"
    vcpassword: "{{ vsphere_vcpassword }}"
    datacenter: "{{ vsphere_datacenter }}"
  register: vsphere_live_hosts

- debug: msg="{{vsphere_live_hosts}}"

- name: msg="Find the VM"
  vsphere_find_vm:
    vcenter: "{{ vsphere_vcenter }}"
    vcusername: "{{ vsphere_vcusername }}"
    vcpassword: "{{ vsphere_vcpassword }}"
    datacenter: "{{ vsphere_datacenter }}"
    datastore: "{{ deploy_datastore }}"
    esxihostname: "{{ execution_host }}"
    vm_name: "{{ vm_name_deploy }}"
    folder_name: "{{ clusterid }}{{ system_versiontag }}"
  register: deployed_vm
