---
- name: Add a VMware vSwitch - {{switch_name}}
  local_action:
    module: hw_vmware_vswitch
    validate_certs: False
    hostname: "{{execution_host}}"
    username: "{{execution_host_username}}"
    password: "{{execution_host_password}}"
    switch_name: "{{switch_name}}"
    nic_name1: "{{nic_name1}}"
    nic_name2: "{{nic_name2}}"    
    state: present  
  when: (nic_name1 is defined) and (nic_name2 is defined)

- name: Add a VMware vSwitch - {{switch_name}}
  local_action:
    module: hw_vmware_vswitch
    validate_certs: False
    hostname: "{{execution_host}}"
    username: "{{execution_host_username}}"
    password: "{{execution_host_password}}"
    switch_name: "{{switch_name}}"
    nic_name1: "{{nic_name1}}"    
    state: present  
  when: nic_name1 is defined

- name: Add a VMware vSwitch - {{switch_name}}
  local_action:
    module: hw_vmware_vswitch
    validate_certs: False
    hostname: "{{execution_host}}"
    username: "{{execution_host_username}}"
    password: "{{execution_host_password}}"
    switch_name: "{{switch_name}}"  
    state: present  
  when: nic_name1 is not defined  