---
- name: create pmjob for {{pmjob_hostname}}
  template:
    src: "pmjob.xml.j2"
    dest: "{{pmjob_dest}}/pmjob-{{pmjob_hostname}}.xml"
    mode: 0755

- name: copy ts pmjob
  delegate_to: "{{pmjob_vm}}"
  copy:
    src: "{{pmjob_dest}}/pmjob-{{pmjob_hostname}}.xml"
    dest: "/usr/local/esa/conf/pmJobs/afg_pmjob.xml"
    owner: miepadm
    group: miepgrp
    mode: 0644  