---
- name: Set timesync attribute
  action:
    module: hw_vsphere_update_vm
    vcenter: "{{ vsphere_vcenter }}"
    vcusername: "{{ vsphere_vcusername }}"
    vcpassword: "{{ vsphere_vcpassword }}"
    vm_name: "{{item}}_template"
    datacenter: "{{ vsphere_datacenter }}"
    datastore: "{{ deploy_datastore }}"
    esxihostname: "{{ execution_host }}"
    time_sync: True
    poweroff_mode: hard
  with_items: "{{vm_types}}"


