---
# VMDK uploaded manually due to long time
#directory: /vsphere_file_root_path/images
- name: Mount vmdk root file system
  action:
    module: vsphere_attach_disk
    vcenter: "{{ vsphere_vcenter }}"
    vcusername: "{{ vsphere_vcusername }}"
    vcpassword: "{{ vsphere_vcpassword }}"
    vm_name: "{{ template_name }}"
    datacenter: "{{ vsphere_datacenter }}"
    datastore: "{{ vsphere_datastore }}"
    esxihostname: "{{ vsphere_esxihostname }}"
    disk_file_path: "/images/MSP7.1_MN.x86_64-R2E-11.20160407.vmdk"



