
- name: make a vmdk name
  find: "path={{vmdk_images_dir}} patterns='{{vmdk_patterns}}'" 
  delegate_to: "{{execution_host}}"
  register: rst      

- name: check files
  set_fact: 
    vmdk_name: "{{rst.files[0].path | regex_replace('^.*/(.*)$', '\\1')}}"  

- name: Mount vmdk root file system for {{vm_name}}
  action:
    module: hw_vsphere_attach_disk
    vcenter: "{{ vsphere_vcenter }}"
    vcusername: "{{ vsphere_vcusername }}"
    vcpassword: "{{ vsphere_vcpassword }}"
    vm_name: "{{vm_name}}"
    datacenter: "{{ vsphere_datacenter }}"
    datastore: "{{ deploy_datastore }}"
    esxihostname: "{{ execution_host }}"
    disk_file_path: "/images/{{vmdk_name}}"

