---
- name: create pmcounter file
  template:
    src: pmcounter.xml.j2
    dest: "{{pmcounter_dest}}/{{pmcounter_filename}}"
    mode: 0755
  with_items:
    - "{{pmcounter_group}}"

- name: upload pmcounters file
  delegate_to: "{{pmcounter_vm}}"
  copy:
    src:  "{{pmcounter_dest}}/{{pmcounter_filename}}"
    dest: "/usr/local/esa/conf/pmCounters/{{pmcounter_filename}}"
    owner: miepadm
    group: miepgrp
    mode: 0644 