---
- name: poweron VM
  vsphere_guest:
    vcenter_hostname: "{{ vsphere_vcenter }}"
    username: "{{ vsphere_vcusername }}"
    password: "{{ vsphere_vcpassword }}"
    guest: "{{item}}"
    state: powered_on
    validate_certs: False
  with_items: "{{vm_names}}" 