---
- name: poweron {{vm_name}}
  vsphere_guest:
    vcenter_hostname: "{{ vsphere_vcenter }}"
    username: "{{ vsphere_vcusername }}"
    password: "{{ vsphere_vcpassword }}"
    guest: "{{vm_name}}"
    state: "{{vm_state}}"
    validate_certs: False