---
- name: msg="Find the VM"
  vsphere_find_vm:
    vcenter: "{{ vsphere_vcenter }}"
    vcusername: "{{ vsphere_vcusername }}"
    vcpassword: "{{ vsphere_vcpassword }}"
    datacenter: "{{ vsphere_datacenter }}"
    datastore: "{{ vsphere_datastore }}"
    esxihostname: "{{ execution_host }}"
    vm_name: "{{vm_type}}_template"
    folder_name: ""
  register: deployed_template

- name: msg="Clean possible existing template"
  vsphere_guest:
    vcenter_hostname: "{{ vsphere_vcenter }}"
    username: "{{ vsphere_vcusername }}"
    password: "{{ vsphere_vcpassword }}"
    guest: "{{vm_type}}_template"
    state: absent
    validate_certs: False
  when: deployed_template.vm_name != ""
