---
- name: Clean existing {{vm_name}}
  vsphere_guest:
    vcenter_hostname: "{{ vsphere_vcenter }}"
    username: "{{ vsphere_vcusername }}"
    password: "{{ vsphere_vcpassword }}"
    guest: "{{vm_name}}"
    state: absent
    validate_certs: False
