---
- name: define domain {{vm_name}}
  virt: 
    name: "{{vm_name}}"
    command: define
    xml: "{{ lookup('template', 'mn.xml.j2') }}"
  when: "'{{vm_type}}' == 'mn'" 

- name: define domain {{vm_name}}
  virt: 
    name: "{{vm_name}}"
    command: define
    xml: "{{ lookup('template', 'mon.xml.j2') }}"
  when: "'{{vm_type}}' == 'mon'" 

- name: define domain {{vm_name}}
  virt: 
    name: "{{vm_name}}"
    command: define
    xml: "{{ lookup('template', 'slb.xml.j2') }}"
  when: "'{{vm_type}}' == 'slb'" 

- name: define domain {{vm_name}}
  virt: 
    name: "{{vm_name}}"
    command: define
    xml: "{{ lookup('template', 'ddc.xml.j2') }}"
  when: "'{{vm_type}}' == 'ddc'" 

- name: define domain {{vm_name}}
  virt: 
    name: "{{vm_name}}"
    command: define
    xml: "{{ lookup('template', 'ts.xml.j2') }}"
  when: "'{{vm_type}}' == 'ts'" 

- name: define domain {{vm_name}}
  virt: 
    name: "{{vm_name}}"
    command: define
    xml: "{{ lookup('template', 'vyos.xml.j2') }}"
  when: "'{{vm_type}}' == 'vyos'"   

- name: start domain {{vm_name}}
  virt:
    name: "{{vm_name}}"
    state: running

