---
- name: get list of domains
  virt: command=list_vms
  register: virt_vms 

- name: create_domain | template
  template:
    dest: "/tmp/mn.xml"
    src: "mn.j2"
  when: not "{{guest}}" in virt_vms.list_vms

- name: create_domain | define
  command: "virsh define /tmp/mn.xml"
  when: not "{{guest}}" in virt_vms.list_vms

#- name: create_domain | start
#  command: "virsh start {{ libvirt_result_domain_name }}"
#  when: "{{guest}}" not in virt_vms.list_vms      
