---
- name: Create a guest template MN
  hw_vsphere_guest:
    vcenter_hostname: "{{ vsphere_vcenter }}"
    username: "{{ vsphere_vcusername }}"
    password: "{{ vsphere_vcpassword }}"
    guest: mn_template
    validate_certs: False
    state: present
    vm_extra_config:
      vcpu.hotadd: no
      mem.hotadd:  no
      notes: "This is a VM for AFG mn_template"
      #folder: "{{vsphere_file_root_path}}"
    vm_disk:
      disk1:
        size_gb: 50
        type: thin
        datastore: "{{ vsphere_datastore }}"
      disk2:
        size_gb: 10
        type: thin
        datastore: "{{ vsphere_datastore }}"
      disk3:
        size_gb: 10
        type: thin
        datastore: "{{ vsphere_datastore }}"
      disk4:
        size_gb: 30
        type: thin
        datastore: "{{ vsphere_datastore }}"
      disk5:
        size_gb: 10
        type: thin
        datastore: "{{ vsphere_datastore }}"
    vm_nic:
      nic1:
        type: vmxnet3
        network: "{{OAM_name}}"
        network_type: standard
      nic2:
        type: vmxnet3
        network: "{{Internal_name}}"
        network_type: standard
    vm_hardware:
      memory_mb: 5120
      num_cpus: 2
      osid: sles11_64Guest
      scsi: lsi
      vm_cdrom:
        - cdrom1:
          type: "iso"
          iso_path: "{{ vsphere_datastore}}/{{vsphere_file_root_path }}/{{ CLUSTER_ID }}/empty.iso"
        - cdrom2:
          type: "iso"
          iso_path: "{{ vsphere_datastore}}/{{vsphere_file_root_path }}/{{ CLUSTER_ID }}/empty.iso"
    esxi:
      datacenter: "{{ vsphere_datacenter }}"
      datastore: "{{ vsphere_datastore }}"
      hostname: "{{ vsphere_esxihostname }}" 
  when: "'mn' in vm_types"

- name: Create a guest template TS
  hw_vsphere_guest:
    vcenter_hostname: "{{ vsphere_vcenter }}"
    username: "{{ vsphere_vcusername }}"
    password: "{{ vsphere_vcpassword }}"
    guest: ts_template
    validate_certs: False
    state: present
    vm_extra_config:
      vcpu.hotadd: no
      mem.hotadd:  no
      notes: "This is a VM for AFG ts_template"
      #folder: "{{vsphere_file_root_path}}"      
    vm_disk:
      disk1:
        size_gb: 30
        type: thin
        datastore: "{{ vsphere_datastore }}"
    vm_nic:
      nic1:
        type: vmxnet3
        network: "{{OAM_name}}"
        network_type: standard
      nic2:
        type: vmxnet3
        network: "{{Access_name}}" 
        network_type: standard
      nic3:
        type: vmxnet3
        network: "{{Internet_name}}"
        network_type: standard
      nic4:
        type: vmxnet3
        network: "{{ControlPlaneSig_name}}"
        network_type: standard
      nic5:
        type: vmxnet3
        network: "{{Internal_name}}"
        network_type: standard
    vm_hardware:
      memory_mb: 6144
      num_cpus: 4
      osid: sles11_64Guest
      scsi: lsi
      vm_cdrom:
        - cdrom1:
          type: "iso"
          iso_path: "{{ vsphere_datastore}}/{{vsphere_file_root_path }}/{{ CLUSTER_ID }}/empty.iso"
        - cdrom2:
          type: "iso"
          iso_path: "{{ vsphere_datastore}}/{{vsphere_file_root_path }}/{{ CLUSTER_ID }}/empty.iso"
    esxi:
      datacenter: "{{ vsphere_datacenter }}"
      datastore: "{{ vsphere_datastore }}"
      hostname: "{{ vsphere_esxihostname }}" 
  when: "'ts' in vm_types"  

- name: Create a guest template DDC
  hw_vsphere_guest:
    vcenter_hostname: "{{ vsphere_vcenter }}"
    username: "{{ vsphere_vcusername }}"
    password: "{{ vsphere_vcpassword }}"
    guest: ddc_template
    validate_certs: False
    state: present
    vm_extra_config:
      vcpu.hotadd: no
      mem.hotadd:  no
      notes: "This is a VM for AFG ddc_template"
      #folder: "{{vsphere_file_root_path}}"      
    vm_disk:
      disk1:
        size_gb: 30
        type: thin
        datastore: "{{ vsphere_datastore }}"
    vm_nic:
      nic1:
        type: vmxnet3
        network: "{{OAM_name}}"
        network_type: standard
      nic2:
        type: vmxnet3
        network: "{{Internal_name}}"
        network_type: standard
      nic3:
        type: vmxnet3
        network: Access
        network_type: standard
    vm_hardware:
      memory_mb: 4096
      num_cpus: 2
      osid: sles11_64Guest
      scsi: lsi
      vm_cdrom:
        - cdrom1:
          type: "iso"
          iso_path: "{{ vsphere_datastore}}/{{vsphere_file_root_path }}/{{ CLUSTER_ID }}/empty.iso"
        - cdrom2:
          type: "iso"
          iso_path: "{{ vsphere_datastore}}/{{vsphere_file_root_path }}/{{ CLUSTER_ID }}/empty.iso"
    esxi:
      datacenter: "{{ vsphere_datacenter }}"
      datastore: "{{ vsphere_datastore }}"
      hostname: "{{ vsphere_esxihostname }}" 
  when: "'ddc' in vm_types"

- name: Create a guest template MON
  hw_vsphere_guest:
    vcenter_hostname: "{{ vsphere_vcenter }}"
    username: "{{ vsphere_vcusername }}"
    password: "{{ vsphere_vcpassword }}"
    guest: mon_template
    validate_certs: False
    state: present
    vm_extra_config:
      vcpu.hotadd: no
      mem.hotadd:  no
      notes: "This is a VM for AFG mon_template"
      #folder: "{{vsphere_file_root_path}}"      
    vm_disk:
      disk1:
        size_gb: 30
        type: thin
        datastore: "{{ vsphere_datastore }}"
    vm_nic:
      nic1:
        type: vmxnet3
        network: "{{OAM_name}}"
        network_type: standard
      nic2:
        type: vmxnet3
        network: "{{Internal_name}}"
        network_type: standard
    vm_hardware:
      memory_mb: 5120
      num_cpus: 2
      osid: sles11_64Guest
      scsi: lsi
      vm_cdrom:
        - cdrom1:
          type: "iso"
          iso_path: "{{ vsphere_datastore}}/{{vsphere_file_root_path }}/{{ CLUSTER_ID }}/empty.iso"
        - cdrom2:
          type: "iso"
          iso_path: "{{ vsphere_datastore}}/{{vsphere_file_root_path }}/{{ CLUSTER_ID }}/empty.iso"
    esxi:
      datacenter: "{{ vsphere_datacenter }}"
      datastore: "{{ vsphere_datastore }}"
      hostname: "{{ vsphere_esxihostname }}" 
  when: "'mon' in vm_types"     