---
- name: attach iso files to VM
  hw_vsphere_cd_iso:
    vcenter: "{{ vsphere_vcenter }}"
    vcusername: "{{ vsphere_vcusername }}"
    vcpassword: "{{ vsphere_vcpassword }}"
    vm_name: "{{ deploy_vm_name }}"
    datacenter: "{{ vsphere_datacenter }}"
    datastore: "{{ vsphere_datastore }}"
    esxihostname: "{{ vsphere_esxihostname }}"
    iso_path: "{{iso_path_input}}"
    unit_number: "{{unit_number_input}}"




