---
- name: attach iso files to {{ deploy_vm_name }} cdrom 0
  hw_vsphere_cd_iso:
    vcenter: "{{ vsphere_vcenter }}"
    vcusername: "{{ vsphere_vcusername }}"
    vcpassword: "{{ vsphere_vcpassword }}"
    vm_name: "{{ deploy_vm_name }}"
    datacenter: "{{ vsphere_datacenter }}"
    datastore: "{{ deploy_datastore }}"
    esxihostname: "{{ execution_host }}"
    iso_path: "{{iso_path_input0}}"
    unit_number: 0

- name: attach iso files to {{ deploy_vm_name }} cdrom 1
  hw_vsphere_cd_iso:
    vcenter: "{{ vsphere_vcenter }}"
    vcusername: "{{ vsphere_vcusername }}"
    vcpassword: "{{ vsphere_vcpassword }}"
    vm_name: "{{ deploy_vm_name }}"
    datacenter: "{{ vsphere_datacenter }}"
    datastore: "{{ deploy_datastore }}"
    esxihostname: "{{ execution_host }}"
    iso_path: "{{iso_path_input1}}"
    unit_number: 1


