---
- block: 
    - name: snmpwalk v2
      command: >
        snmpwalk
        -v 2c
        -c ESA-PC
        "{{vm_oam_ip}}":3161
        "1.3.6.1.2.1.1"
        -On
      register: rst
      
    - name: snmpwalk v2
      debug: msg="{{rst.stdout_lines}}"

    - name: snmpwalk v3
      command: >
        snmpwalk
        -v 3
        -n ""
        -u v3AuthSHAPrivDESSecName
        -a SHA
        -A v3AuthSHAPrivDESAuthPassword
        -x DES
        -X v3AuthSHAPrivDESPrivPassword
        -l authPriv
        "{{vm_oam_ip}}":3161
        "1.3.6.1.2.1.1"            
        -On
      register: rst
      
    - name: snmpwalk v3
      debug: msg="{{rst.stdout_lines}}"  
              
  become: Yes
  delegate_to: "{{vm_oam_ip}}"