---
- name: Expand root disk 0 of {{ deploy_vm_name }}
  hw_vsphere_expand_disk:
    vcenter: "{{ vsphere_vcenter }}"
    vcusername: "{{ vsphere_vcusername }}"
    vcpassword: "{{ vsphere_vcpassword }}"
    datacenter: "{{ vsphere_datacenter }}"
    datastore: "{{ deploy_datastore }}"
    disk_id: 0
    disk_size: "{{disk_size}}"   
    esxihostname: "{{ execution_host }}"
    folder_name: "{{ folder_name }}"
    vm_name: "{{ deploy_vm_name }}"



