---
- name: Clone {{template_src}} --> {{guest_vm}}
  vsphere_guest:
    vcenter_hostname: "{{ vsphere_vcenter }}"
    username: "{{ vsphere_vcusername }}"
    password: "{{ vsphere_vcpassword }}"
    guest: "{{guest_vm}}"
    validate_certs: False
    from_template: yes
    cluster: afg_cluster
    template_src: "{{template_src}}"
    power_on_after_clone: False
    esxi:
      datacenter: "{{ vsphere_datacenter }}"
      datastore: "{{ deploy_datastore }}"
      hostname: "{{ execution_host }}"        

 