---
- name: combine all attributes group
  set_fact:
    afg_attr: "{{ afg_attr|default({})|combine(item.value) }}"
  with_dict: "{{afg_attributes}}"

- name: set/audit afg attribute
  afg_attribute: 
    attribute_cluster: "{{CLUSTER_ID}}"
    attribute: "{{item.key}}"
    attribute_value: "{{item.value}}" #GET,PUT,POST,DELETE
    #attribute_confirm: False 
  with_dict: "{{afg_attr}}"  
