---
- name: grab file list
  find: path="{{output_dir}}" patterns="*/" file_type="directory" 
  register: rst         

- name: set fact
  set_fact: 
    vm_names: "{{vm_names | default([]) + [item.path | regex_replace('^.*/(.*)$', '\\1')] }}"
  with_items: "{{rst.files}}"

- name: Upload {{HOSTNAME_OF_MN_VM}} IID .iso file to vSphere
  vsphere_copy:
    validate_certs: false
    src: "{{ output_dir }}/{{ item }}/{{ item }}.iso"
    path: "{{vsphere_file_root_path}}/iid/{{ item }}.iso"
    host: "{{ vsphere_vcenter }}"
    login: "{{ vsphere_vcusername }}"
    password: "{{ vsphere_vcpassword }}"
    datacenter: "{{ vsphere_datacenter }}"
    datastore: "{{ deploy_datastore }}"
  with_items: "{{vm_names}}" 