---
- name: msg="Upload IID .iso file to vSphere"
  vsphere_loadfile:
    src: "{{ output_dir }}/{{ item }}/{{ item }}.iso"
    dest: "{{vsphere_file_root_path}}/iid/{{ item }}.iso"
    vsphere_vcenter: "{{ vsphere_vcenter }}"
    vsphere_vcusername: "{{ vsphere_vcusername }}"
    vsphere_vcpassword: "{{ vsphere_vcpassword }}"
    vsphere_datacenter: "{{ vsphere_datacenter }}"
    vsphere_datastore: "{{ deploy_datastore }}"
    vsphere_esxihostname: "{{ execution_host }}"
  with_items: 
    - "{{HOSTNAME_OF_MN_VM}}"
    - "{{HOSTNAME_OF_TS_VM}}"
    - "{{HOSTNAME_OF_DDC_VM}}"
    - "{{HOSTNAME_OF_MON_VM}}"

