---
- name: Gen AFG attributes command file at {{ output_dir }}
  template: 
    src: afg_database.j2 
    dest: "{{output_dir}}/afg.sql" 
    mode: 0644

- name: copy afg.sql
  copy: 
    src: "{{output_dir}}/afg.sql"
    dest: /var/tmp/afg.sql
    mode: 0644
  delegate_to: "{{IPV4_ADDRESS_OF_OAM_MN}}"  
  register: rst      

- name: import data
  shell: su -s /bin/bash - msausr -c "PGPASSWORD=wapwap12 psql -U msa < /var/tmp/afg.sql"
  delegate_to: "{{IPV4_ADDRESS_OF_OAM_MN}}"
  when: "{{rst.changed}}" 
  register: rst
- debug: msg="{{rst.stdout_lines}}"
  when: "{{rst.changed}}"       

