---
- name: check if the file exist
  stat: path="{{ image_dir }}/{{ img_name }}"
  register: st

- name: "{{ image_dir }}/{{ img_name }} | copy"
  command: >
    cp
    {{base_image_dir}}/{{ img_name }}
    {{ img_name }}
  args:
    chdir: "{{ image_dir }}"
  when: not {{st.stat.exists}}  

- name: "{{ image_dir }}/{{ img_name }} | resize"
  command: >
    qemu-img resize
    {{ img_name }}
    {{ new_size }}
  args:
    chdir: "{{ image_dir }}"
  when: not {{st.stat.exists}}     
